### ISSUE TITLE
Scrollbar issue on chrome

### ISSUE THREAD

**Issue by OmerSabic** [Project-Skill-Tree/Skill-Tree-Editor#3]
Problem: Scrollbar looks weird for all the div containers on specific browsers / browser versions. Default CSS values on browsers are different apparently. 

How to fix: Approve my pull request.

**Comment by swatarianess** [comment]
> _No description provided._

Add a description (What needs to be done and why) and acceptance criteria (what criteria for this issue to be resolved)
