### ISSUE TITLE
Add a way to manipulate the "requires" and "goals" fields.

### ISSUE THREAD

**Issue by OmerSabic** [Project-Skill-Tree/Skill-Tree-Editor#8]
- [ ] Goals field should be an array
- [ ] Add a way to manipulate them without manually writing an array

Some input field with a button and ul that lists the data in that field.

**Comment by seanjhardy** [comment]
A comma-separated list would be fine IMO, doesn't need to be dynamic or fancy or anything. Although you've got to watch out for commas in the goals themselves
